### PR TITLE
parallel API collection pull request

### PR DESCRIPTION
**Pull request by jake-oci**
Signed-off-by: Jake Bloom jake.bloom@oracle.com
git commit --signoff

### CODE REVIEW

**Comment by jake-oci** [comment]
Signed-off-by: Jake Bloom [jake.bloom@oracle.com](mailto:jake.bloom@oracle.com)
git commit --signoff

**Review by adizohar — COMMENTED** [review]
Hi Jake

Please run flake8 on the code and fix the code to comply with flake8 standards
You can ignore E501,W504

Thank you

**Comment by jake-oci** [comment]
@adizohar Let me know if there is anything else. Thank you.

**Comment by adizohar** [comment]
Thank you Jake, I will leave it to OCI SDK team to merge, they may have additional requirements.

**Comment by jake-oci** [comment]
Signed-off-by: Jake Bloom [jake.bloom@oracle.com](mailto:jake.bloom@oracle.com)
git commit --signoff

**Comment by jake-oci** [comment]
Internal merge via Bitbucket

**Comment by bhagwatvyas** [comment]
Thanks for your contribution, @jake-oci!

**Pull request closed without merging**
