### PR TITLE
usage2adw - remove prd_resource from OCI_COST

### PR DESCRIPTION
**Pull request by jhult**
It is never used/populated

### CODE REVIEW

**Review by adizohar — COMMENTED** [review]
We cannot remove this attribute because it is part of the cost file and may have data in the future. Additional application will fail without this field, cannot approve the merge.

**Comment by jhult** [comment]
If it is required, don't you need to put data into that column?

**Comment by adizohar** [comment]
Jonathan, field is in the file, it is saved for future enhancement, I cannot remove it from the code, if it is not filled, it does not take space, What exactly the issue having the field there ? does it cause any issue ?

**Comment by jodoglevy** [comment]
I'm going to close this, since we haven't heard back in a long time from the reporter, and the owner of usage2adw thinks the existing behavior is ok

**Pull request closed without merging**
