### PR TITLE
Update step_by_step_howto.md

### PR DESCRIPTION
**Pull request by xjuarez**
cambios en chmod linea 453 y 454 
y se agrego run_daily_report.sh en el crontab linea 443

### CODE REVIEW

**Review by adizohar — APPROVED** [review]

**Comment by adizohar** [comment]
Thank you Xavier, I will merge it myself, will be done for next Tue.

**Review by adizohar — APPROVED** [review]

**Comment by adizohar** [comment]
Approved

**Review by bhagwatvyas — APPROVED** [review]

**Comment by bhagwatvyas** [comment]
@xjuarez looks like there are conflicts after the latest release. Can you please take a look?

**Review by adizohar — APPROVED** [review]

**Comment by adizohar** [comment]
Approved

**Review by bhagwatvyas — APPROVED** [review]

**Pull request merged**
